baseURL = 'https://jecisc.github.io/'
locale = 'en-US'
title = 'Cyril Ferlicot'
theme = 'mana'
defaultContentLanguage = 'en'

[pagination]
  pageSize = 10

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = 'catppuccin-macchiato'

[outputs]
  home = ['HTML', 'JSON']

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[params]
  enableIntegrity = false
  relatedPostsCount = 3
  description = 'I’m a software engineer publishing about random things, probably around Pharo Smalltalk'
  author = 'Cyril Ferlicot-Delbecque'
  heroTitleLine1 = 'Cyril’s blog'
  heroTitleLine2 = 'To anything'
  footerText = 'Built with Hugo and Mana theme'

  [params.social]
    github = 'https://github.com/jecisc'
    twitter = "jecisc1"
    email = "cyril@ferlicot.fr"

  [params.avatar]
    assetPath = "images/jecisc.png"
    # enableResize = true  # Set false to preserve original size

  [params.avatar.about]
    assetPath = "images/me.png"
    enableResize = true

  [params.favicons]
    ico = "/favicons/favicon.ico"
    #png = "/favicons/favicon.png"
    png16 = "/favicons/favicon-16x16.png"
    png32 = "/favicons/favicon-32x32.png"
    apple180 = "/favicons/apple-touch-icon.png"
    android192 = "/favicons/android-chrome-192x192.png"
    android512 = "/favicons/android-chrome-512x512.png"
    manifest = "/favicons/site.webmanifest"


  [params.codeHighlight]
    darkTheme = 'catppuccin-macchiato'
    lightTheme = 'catppuccin-frappe'

  [params.copyright]
    startYear = 2026
    owner = 'Cyril Ferlicot-Delbecque'

  [params.admonitions]
    alertStyle = 'favicon'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 40
